import { ExtendedSpecConfig } from '../cli';
import { Tsoa, assertNever, Swagger } from '@fastcomments/tsoa-runtime';
import * as handlebars from 'handlebars';
import { GenerateMetadataError } from '../metadataGeneration/exceptions';

export abstract class SpecGenerator {
  constructor(
    protected readonly metadata: Tsoa.Metadata,
    protected readonly config: ExtendedSpecConfig,
  ) {}

  /**
   * OpenAPI requires operationIds to be unique across the whole document, but tsoa derives them from
   * the (per-controller) method name by default, so two controllers with a like-named method silently
   * emit a duplicate operationId. Downstream SDK generators then fail or mis-name types. Detect this up
   * front and throw a clear error pointing at the colliding methods.
   */
  protected checkForDuplicateOperationIds() {
    const operationIdToMethods: { [operationId: string]: string[] } = {};
    this.metadata.controllers.forEach(controller => {
      controller.methods.forEach(method => {
        const operationId = method.operationId || this.getOperationId(controller.name, method);
        const location = `${controller.name}#${method.name}`;
        (operationIdToMethods[operationId] = operationIdToMethods[operationId] || []).push(location);
      });
    });

    const messages: string[] = [];
    Object.keys(operationIdToMethods).forEach(operationId => {
      const locations = operationIdToMethods[operationId];
      if (locations.length > 1) {
        messages.push(`Duplicate operationId "${operationId}" generated by: ${locations.join(', ')}. Rename a method or set a unique @OperationId(...).`);
      }
    });

    if (messages.length) {
      throw new GenerateMetadataError(messages.join('\n'));
    }
  }

  /**
   * For each success response whose schema is a union that includes a configured error type
   * (config.errorResponseTypeNames, e.g. ["APIError"]), keep the success member(s) as the response
   * schema and split the error member(s) out into a `default` error response. This keeps the 2xx
   * response as the real success type instead of an `X | APIError` wrapper, so SDK generators don't
   * synthesize (and collide on) per-operation wrapper models.
   */
  protected splitErrorResponses(method: Tsoa.Method): Tsoa.Response[] {
    const errorTypeNames = this.config.errorResponseTypeNames;
    if (!errorTypeNames || errorTypeNames.length === 0) {
      return method.responses;
    }

    const isErrorRef = (t: Tsoa.Type): boolean => (t.dataType === 'refObject' || t.dataType === 'refAlias' || t.dataType === 'refEnum') && errorTypeNames.includes(t.refName);

    const result: Tsoa.Response[] = [];
    let defaultAdded = method.responses.some(r => r.name === 'default');

    for (const res of method.responses) {
      const schema = res.schema;
      if (schema && schema.dataType === 'union') {
        const errorMembers = schema.types.filter(isErrorRef);
        const successMembers = schema.types.filter(t => !isErrorRef(t));
        if (errorMembers.length > 0 && successMembers.length > 0) {
          result.push({
            ...res,
            schema: successMembers.length === 1 ? successMembers[0] : { ...schema, types: successMembers },
          });
          if (!defaultAdded) {
            result.push({
              name: 'default',
              description: 'Error',
              schema: errorMembers.length === 1 ? errorMembers[0] : { ...schema, types: errorMembers },
            });
            defaultAdded = true;
          }
          continue;
        }
      }
      result.push(res);
    }

    return result;
  }

  protected buildAdditionalProperties(type: Tsoa.Type) {
    return this.getSwaggerType(type);
  }

  protected buildOperationIdTemplate(inlineTemplate: string) {
    handlebars.registerHelper('titleCase', (value: string) => (value ? value.charAt(0).toUpperCase() + value.slice(1) : value));
    handlebars.registerHelper('replace', (subject: string, searchValue: string, withValue = '') => (subject ? subject.replace(searchValue, withValue) : subject));
    return handlebars.compile(inlineTemplate, { noEscape: true });
  }

  protected getOperationId(controllerName: string, method: Tsoa.Method) {
    return this.buildOperationIdTemplate(this.config.operationIdTemplate ?? '{{titleCase method.name}}')({
      method,
      controllerName,
    });
  }

  public throwIfNotDataFormat(strToTest: string): Swagger.DataFormat {
    const guiltyUntilInnocent = strToTest as Swagger.DataFormat;
    if (
      guiltyUntilInnocent === 'int32' ||
      guiltyUntilInnocent === 'int64' ||
      guiltyUntilInnocent === 'float' ||
      guiltyUntilInnocent === 'double' ||
      guiltyUntilInnocent === 'byte' ||
      guiltyUntilInnocent === 'binary' ||
      guiltyUntilInnocent === 'date' ||
      guiltyUntilInnocent === 'date-time' ||
      guiltyUntilInnocent === 'password'
    ) {
      return guiltyUntilInnocent;
    } else {
      return assertNever(guiltyUntilInnocent);
    }
  }

  public throwIfNotDataType(strToTest: string): Swagger.DataType {
    const guiltyUntilInnocent = strToTest as Swagger.DataType;
    if (
      guiltyUntilInnocent === 'array' ||
      guiltyUntilInnocent === 'boolean' ||
      guiltyUntilInnocent === 'integer' ||
      guiltyUntilInnocent === 'file' ||
      guiltyUntilInnocent === 'number' ||
      guiltyUntilInnocent === 'object' ||
      guiltyUntilInnocent === 'string' ||
      guiltyUntilInnocent === 'undefined'
    ) {
      return guiltyUntilInnocent;
    } else {
      return assertNever(guiltyUntilInnocent);
    }
  }

  protected getSwaggerType(type: Tsoa.Type, title?: string): Swagger.Schema | Swagger.BaseSchema {
    if (type.dataType === 'void' || type.dataType === 'undefined') {
      return this.getSwaggerTypeForVoid(type.dataType);
    } else if (type.dataType === 'refEnum' || type.dataType === 'refObject' || type.dataType === 'refAlias') {
      return this.getSwaggerTypeForReferenceType(type);
    } else if (
      type.dataType === 'any' ||
      type.dataType === 'binary' ||
      type.dataType === 'boolean' ||
      type.dataType === 'buffer' ||
      type.dataType === 'byte' ||
      type.dataType === 'date' ||
      type.dataType === 'datetime' ||
      type.dataType === 'double' ||
      type.dataType === 'float' ||
      type.dataType === 'file' ||
      type.dataType === 'integer' ||
      type.dataType === 'long' ||
      type.dataType === 'object' ||
      type.dataType === 'string'
    ) {
      return this.getSwaggerTypeForPrimitiveType(type.dataType);
    } else if (type.dataType === 'array') {
      return this.getSwaggerTypeForArrayType(type, title);
    } else if (type.dataType === 'enum') {
      return this.getSwaggerTypeForEnumType(type, title);
    } else if (type.dataType === 'union') {
      return this.getSwaggerTypeForUnionType(type, title);
    } else if (type.dataType === 'intersection') {
      return this.getSwaggerTypeForIntersectionType(type, title);
    } else if (type.dataType === 'nestedObjectLiteral') {
      return this.getSwaggerTypeForObjectLiteral(type, title);
    } else {
      return assertNever(type);
    }
  }

  protected abstract getSwaggerTypeForUnionType(type: Tsoa.UnionType, title?: string): Swagger.Schema | Swagger.BaseSchema;

  protected abstract getSwaggerTypeForIntersectionType(type: Tsoa.IntersectionType, title?: string): Swagger.Schema | Swagger.BaseSchema;

  protected abstract buildProperties(properties: Tsoa.Property[]): { [propertyName: string]: Swagger.Schema | Swagger.Schema3 };

  public getSwaggerTypeForObjectLiteral(objectLiteral: Tsoa.NestedObjectLiteralType, title?: string): Swagger.Schema {
    const properties = this.buildProperties(objectLiteral.properties);

    const additionalProperties = objectLiteral.additionalProperties && this.getSwaggerType(objectLiteral.additionalProperties);

    const required = objectLiteral.properties.filter(prop => this.isRequiredWithoutDefault(prop) && !this.hasUndefined(prop)).map(prop => prop.name);

    // An empty list required: [] is not valid.
    // If all properties are optional, do not specify the required keyword.
    return {
      ...(title && { title }),
      properties,
      ...(additionalProperties && { additionalProperties }),
      ...(required && required.length && { required }),
      type: 'object',
    };
  }

  protected getSwaggerTypeForReferenceType(_referenceType: Tsoa.ReferenceType): Swagger.BaseSchema {
    return {
      // Don't set additionalProperties value here since it will be set within the $ref's model when that $ref gets created
    };
  }

  protected getSwaggerTypeForVoid(_dataType: 'void' | 'undefined'): Swagger.BaseSchema {
    // Described here: https://swagger.io/docs/specification/describing-responses/#empty
    const voidSchema = {
      // isn't allowed to have additionalProperties at all (meaning not a boolean or object)
    };
    return voidSchema;
  }

  protected determineImplicitAdditionalPropertiesValue = (): boolean => {
    if (this.config.noImplicitAdditionalProperties === 'silently-remove-extras') {
      return false;
    } else if (this.config.noImplicitAdditionalProperties === 'throw-on-extras') {
      return false;
    } else if (this.config.noImplicitAdditionalProperties === 'ignore') {
      return true;
    } else {
      return assertNever(this.config.noImplicitAdditionalProperties);
    }
  };

  protected getSwaggerTypeForPrimitiveType(dataType: Tsoa.PrimitiveTypeLiteral): Swagger.Schema {
    if (dataType === 'object') {
      if (process.env.NODE_ENV !== 'tsoa_test') {
        // eslint-disable-next-line no-console
        console.warn(`The type Object is discouraged. Please consider using an interface such as:
          export interface IStringToStringDictionary {
            [key: string]: string;
          }
          // or
          export interface IRecordOfAny {
            [key: string]: any;
          }
        `);
      }
    }

    const map: Record<Tsoa.PrimitiveTypeLiteral, Swagger.Schema> = {
      any: {
        // While the any type is discouraged, it does explicitly allows anything, so it should always allow additionalProperties
        additionalProperties: true,
      },
      binary: { type: 'string', format: 'binary' },
      boolean: { type: 'boolean' },
      buffer: { type: 'string', format: 'byte' },
      byte: { type: 'string', format: 'byte' },
      date: { type: 'string', format: 'date' },
      datetime: { type: 'string', format: 'date-time' },
      double: { type: 'number', format: 'double' },
      file: { type: 'file' },
      float: { type: 'number', format: 'float' },
      integer: { type: 'integer', format: 'int32' },
      long: { type: 'integer', format: 'int64' },
      object: {
        additionalProperties: this.determineImplicitAdditionalPropertiesValue(),
        type: 'object',
      },
      string: { type: 'string' },
    };

    return map[dataType];
  }

  protected getSwaggerTypeForArrayType(arrayType: Tsoa.ArrayType, title?: string): Swagger.Schema {
    return {
      items: this.getSwaggerType(arrayType.elementType, title),
      type: 'array',
    };
  }

  protected determineTypesUsedInEnum(anEnum: Array<string | number | boolean | null>) {
    const allNumbersAreIntegers = anEnum.every(v => typeof v !== 'number' || Number.isInteger(v));
    const typesUsedInEnum = anEnum.reduce((theSet, curr) => {
      let typeUsed: 'string' | 'number' | 'boolean' | 'integer';
      if (curr === null || typeof curr === 'number') {
        typeUsed = allNumbersAreIntegers ? 'integer' : 'number';
      } else {
        typeUsed = typeof curr as 'string' | 'boolean';
      }
      theSet.add(typeUsed);
      return theSet;
    }, new Set<'string' | 'number' | 'boolean' | 'integer'>());

    return typesUsedInEnum;
  }

  protected abstract getSwaggerTypeForEnumType(enumType: Tsoa.EnumType, title?: string): Swagger.Schema2 | Swagger.Schema3;

  protected hasUndefined(property: Tsoa.Property): boolean {
    return property.type.dataType === 'undefined' || (property.type.dataType === 'union' && property.type.types.some(type => type.dataType === 'undefined'));
  }

  protected queriesPropertyToQueryParameter(property: Tsoa.Property): Tsoa.Parameter {
    return {
      parameterName: property.name,
      example: [property.example as any],
      description: property.description,
      in: 'query',
      name: property.name,
      required: this.isRequiredWithoutDefault(property),
      type: property.type,
      default: property.default,
      validators: property.validators,
      deprecated: property.deprecated,
    };
  }

  protected isRequiredWithoutDefault(prop: Tsoa.Property | Tsoa.Parameter): boolean | undefined {
    return prop.required && prop.default == null;
  }
}
