import 'mocha';
import { expect } from 'chai';
import { MetadataGenerator } from '@fastcomments/tsoa-cli/metadataGeneration/metadataGenerator';
import { SpecGenerator3 } from '@fastcomments/tsoa-cli/swagger/specGenerator3';
import { SpecGenerator2 } from '@fastcomments/tsoa-cli/swagger/specGenerator2';
import { ExtendedSpecConfig } from '@fastcomments/tsoa-cli/cli';
import { getDefaultExtendedOptions } from '../../fixtures/defaultOptions';

describe('Duplicate operationIds', () => {
  const metadata = new MetadataGenerator('./fixtures/controllers/duplicateOperationIdController.ts').Generate();
  const options: ExtendedSpecConfig = getDefaultExtendedOptions();

  it('should reject methods that generate the same operationId (OpenAPI 3)', () => {
    expect(() => {
      new SpecGenerator3(metadata, options).GetSpec();
    }).to.throw('Duplicate operationId "GetModel" generated by: DuplicateOperationIdAController#getModel, DuplicateOperationIdBController#getModel');
  });

  it('should reject methods that generate the same operationId (OpenAPI 2)', () => {
    expect(() => {
      new SpecGenerator2(metadata, options).GetSpec();
    }).to.throw('Duplicate operationId "GetModel"');
  });

  it('should allow distinct operationIds', () => {
    const okMetadata = new MetadataGenerator('./fixtures/controllers/getController.ts').Generate();
    expect(() => {
      new SpecGenerator3(okMetadata, options).GetSpec();
    }).to.not.throw();
  });
});
